server:
  port: 8080
spring:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/p2p?useUnicode=true&characterEncoding=utf-8
      username: root
      password: teng